let albums = [
    {
        title: `Pirokinesis`,
        img: `assets/1.jpg`,
        year: `2023`,
        description: `успокаюващие`,
        tracks: [
            {
            title: `Молот ведьм`,
            author: `Pirokinesis`,
            time: `2:40`,
            src:`music/Молот_ведьм.opus`,
            isPlaying: false,
        },
        {
            title: `Звёзы все принадлежат богам`,
            author: `Pirokinesis`,
            time: `3:16`,
            src:`music/Звёзды_все_принадлежат_богам.mp3`,
            isPlaying: false,
        },
        {
            title: `Стотысячекрылым`,
            author: `Pirokinesis`,
            time: `5:34`,
            src:`music/Стотысячекрылым.mp3`,
            isPlaying: false,
        },
        {
            title: `Прикоснувшиеся к солнцу`,
            author: `Pirokinesis`,
            time: `2:40`,
            src:`music/Прикоснувшиеся_к_солнцу.mp3`,
            isPlaying: false,
        },
        ],
    },
    {
        title: `О любви`,
        img: `assets/2.jpg`,
        year: `2023`,
        description: `мой альбом`,
        tracks: [
            {
            title: `Сигоретка без кнопки`,
            author: `Pirokinesis`,
            time: `3:03`,
            src:`music/Сигоретка_без_кнопки.mp3`,
            isPlaying: false,
        },
        {
            title: `Любовь в таблетках`,
            author: `Pirokinesis`,
            time: `3:09`,
            src:`music/Любовь_в_таблетках.mp3`,
            isPlaying: false,
        },
        {
            title: `Девочка Петербурга`,
            author: `Monrau`,
            time: `3:41`,
            src:`music/Девочка_петербурга.mp3`,
            isPlaying: false,
        },
        ],
    },
    {
        title: `Fizica`,
        img: `assets/3.jpg`,
        year: `2023`,
        description: `мой альбом`,
        tracks: [
            {
            title: `Русский аристократ`,
            author: `Fizica`,
            time: `2:23`,
            src:`music/Русский_аристократ.mp3`,
            isPlaying: false,
        },
        {
            title: `Грешница`,
            author: `Fizica`,
            time: `2:16`,
            src:`music/Грешница.mp3`,
            isPlaying: false,
        },
        {
            title: `Готэм`,
            author: `Fizica`,
            time: `3:37`,
            src:`music/Готэм.mp3`,
            isPlaying: false,
        },
        ],
    },
    {
        title: `Дедлайн`,
        img: `assets/4.jpg`,
        year: `2023`,
        description: `Скоро дедлайн`,
        tracks: [
            {
            title: `Дедлайны`,
            author: `Pirokinesis`,
            time: `6:06`,
            src:`music/Дедлайны.mp3`,
            isPlaying: false,
        },
        {
            title: `Останови меня`,
            author: `Pirokinesis`,
            time: `3:32`,
            src:`music/Останови_меня.mp3`,
            isPlaying: false,
        },
        ],
    },
]